pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
    }
}

//core game code modules
include ':SPD-classes'
include ':core'

//platform modules
include ':android'
include ':ios'
include ':desktop'
include ':web'

//service modules
include ':services'
    //updates
    include ':services:updates:debugUpdates'
    include ':services:updates:githubUpdates'
    //news
    include ':services:news:debugNews'
    include ':services:news:shatteredNews'
